### ISSUE TITLE
Cannot apply a Request Redirect rule, after a Replace Host rule 

### ISSUE THREAD

**Issue by carpii** [requestly/customer-support#55]
I have a Replace Host rule which replaces domain.com with old.domain.com

I then have a Request Redirect rule which redirects old.domain.com/something to old.domain.com/somethingelse

It seems like Requestly will only run the first rule, and then stop processing (the 2nd rule never kicks in).

**Comment by carpii** [comment]
The two rules are as follows...

````
[
  {
    "creationDate": 1583702175735,
    "description": "",
    "groupId": "",
    "id": "Replace_1583702175735",
    "isSample": false,
    "name": "Replace reddit.com with old.reddit.com",
    "objectType": "rule",
    "pairs": [
      {
        "from": "reddit.com",
        "source": {
          "key": "host",
          "operator": "Equals",
          "value": "reddit.com"
        },
        "status": "Inactive",
        "to": "old.reddit.com"
      },
      {
        "from": "www.reddit.com",
        "source": {
          "filters": {},
          "key": "host",
          "operator": "Equals",
          "value": "www.reddit.com"
        },
        "status": "Inactive",
        "to": "old.reddit.com"
      }
    ],
    "ruleType": "Replace",
    "status": "Active",
    "version": 2
  }
]
````

````
[
  {
    "creationDate": 1581198872473,
    "description": "",
    "groupId": "",
    "id": "Redirect_1581198872473",
    "isSample": false,
    "name": "Show reddit hot instead of best",
    "objectType": "rule",
    "pairs": [
      {
        "destination": "https://old.reddit.com/hot",
        "source": {
          "filters": {},
          "key": "Url",
          "operator": "Equals",
          "value": "https://old.reddit.com/"
        }
      }
    ],
    "ruleType": "Redirect",
    "status": "Active"
  }
]
````

**Comment by requestly-team** [comment]
Hey @carpii Thanks for reaching out. We made a change back in Jan'2018 for performance reasons that two rules won't be applied to a single request URL.

Here's the article we published explaining the difference between Multiple Pairs and Multiple Rules in Requestly - https://medium.com/requestly-docs/multiple-rules-vs-multiple-modification-pairs-in-a-single-rule-in-requestly-f3ec5b1559ff

You can achieve this use case with a single Replace Rule like this

<img width="1086" alt="Screenshot 2020-03-22 17 30 04" src="https://user-images.githubusercontent.com/35186614/77248857-c707e680-6c62-11ea-8876-fff68a825cfe.png">

Here's a SharedList URL for a single click import of above Rule - https://app.requestly.in/rules/#sharedList/1584878432436-old-reddit-rules

Steps to Get the Rule
1. Click on the link
2. Click on Import List

Just in case you are wondering how to use SharedList feature, here's the documentation - https://www.requestly.in/blog/2018/06/14/share-rules-with-other-users/

**Comment by carpii** [comment]
@requestly-team Thanks for the reply, and sample rules

I didn't know you could chain rule actions like this, which is pretty cool.
It is working a lot better, but still not 100%... if I type reddit.com into my Chrome address bar, the rules forward me https://old.reddit.com but the last rule (in your shared rule) does not then redirect it to /hot

Once it has loaded, clicking the Best tab on reddit, will redirect to /hot. 

Thanks

**Comment by requestly-team** [comment]
Thanks @carpii for getting back on this. This looks like a bug on our end. We are looking into it. Will keep you posted.

**Comment by requestly-team** [comment]
@carpii We checked on this. There was a small modification required in order to make this work.

<img width="1089" alt="Screenshot 2020-03-25 12 14 54" src="https://user-images.githubusercontent.com/35186614/77509175-45969b00-6e92-11ea-8813-b19ca125fe61.png">

Please import this list - https://app.requestly.in/rules/#sharedList/1585118604094-Reddit-Rule-v2

This is the justification

When we intercept the URL and modify reddit.com with old.reddit.com, after that Chrome upgrades the protocol to https://old.reddit.com and then the request is not passed further to zny extension for modification

When we intercept the https://reddit.com, protocol upgrade happens first and then given to Requestly for modification. At that point, we modify https://reddit.com to https://old.reddit.com and consequently further pairs are also applied.

Please try this and let us know if it works at your end.

**Comment by carpii** [comment]
@ requestly-team this is now working

Thanks for the great support, will be renewing Premium when the time comes.

Cheers

**Comment by requestly-team** [comment]
Thanks @carpii for the response. Love to hear you will be renewing premium plan. 

Can you please rate our product & response on Chrome Store - https://chrome.google.com/webstore/detail/requestly-redirect-url-mo/mdnleldcmiljblolnjhpnblkcekpdkpa?hl=en ?

**Comment by carpii** [comment]
@requestly-team - no probs. It turns out I had already submitted a review some time ago, but have edited it and resubmitted, so it appears more recent.

**Comment by requestly-team** [comment]
Thank you so much @carpii for the feedback. We will brainstorm about providing rule priority feature.
